calendar:
  key: AIzaSyD7A3BcJKsHCB7XEoGxQ5BGIhYhF0P42fA
  1a: 169u8pr5vrf296hmigiehltr8o@group.calendar.google.com
  2a: cmr96jsu22k4qs7mh0akh6u9vc@group.calendar.google.com
  2ao: 0n50q3l187pmjujgooeuq1ajmo@group.calendar.google.com
  3a: k9lf59hq805o5enoo01mhjv9m8@group.calendar.google.com
  3ao: attente
  bde: lhonilnm3lvk7o4g1d556pf1hk@group.calendar.google.com
