# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e44353d5b5cca5026893cffdf65958b5bfb6c762b8bb5d06fdd7c825c139a3b4eb1df948365917dc41b9da62b67e0c1c29c6411ec87ba4de5cb1509f3c20b1e2

test:
  secret_key_base: cf2047edc26968cd294881e9dfe651d27b3e4023d6e546e47891dd6952625c32e3b13b492b5534c17b205cc5bc04adb97c38be8e60a159790e4b483d3a2da4dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
